--filein ((getDir #userscripts) + "\DebrisMaker2\includes\globals.mse")
--filein ((getDir #userscripts) + "\DebrisMaker2\includes\functions.mse")
--filein ((getDir #userscripts) + "\DebrisMaker2\includes\ui.mse")
 --print "DebrisMaker Initalized"
filein ("C:\\Users\\PC-0253user\\Documents\\GitHub\\Trunk\\MAX\\MAXscript\\MADOKA\\include\\global.ms")
filein ("C:\\Users\\PC-0253user\\Documents\\GitHub\\Trunk\\MAX\\MAXscript\\MADOKA\\include\\ui.ms")
filein ("C:\\Users\\PC-0253user\\Documents\\GitHub\\Trunk\\MAX\\MAXscript\\MADOKA\\include\\main.ms")
filein ("C:\\Users\\PC-0253user\\Documents\\GitHub\\Trunk\\MAX\\MAXscript\\MADOKA_CA\\stdplugs\\stdscripts\\madoka\\ghostsetting.ms")