global madokaFn
global main_rollout
global Patty
global checkBoxState
------------------------------------------
global Cecilia_list_obj
global xtrabonesarr 
global VersionInfo = "Version : 0.9b"
global scriptroot = (getDir #scripts) + "\\Madoka\\"
global madokaINI_Path = scriptroot + "\\madoka.ini"
global CA_scriptroot = scriptroot + "\\characterize\\"
global madokaCA_Path = CA_scriptroot + "\\CAmain.ms"